title: "Think Flow"
email: Wimp8322@proton.me
timezone: UTC
baseurl: ''
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
future: true
# author: Think Flow
paginate: 30
# disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
#authors:
  #sal:
  #  name: Sal
  #  display_name: Sal
  #  avatar: 'assets/images/sal.png'
  #  email: 
  #  web: https://www.thinkflow.me
  #  twitter: https://twitter.com/thinkflowme
  #  description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  

# Social
social:
  instagram: https://www.instagram.com/thinkflowme/
  twitter: https://twitter.com/thinkflowme

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
